# permissions for end users to view ec2instances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ec2instance-viewer-role
rules:
- apiGroups:
  - cloudf.cloudfdomain
  resources:
  - ec2instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudf.cloudfdomain
  resources:
  - ec2instances/status
  verbs:
  - get
