
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloudf.cloudfdomain
  resources:
  - ec2instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudf.cloudfdomain
  resources:
  - ec2instances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudf.cloudfdomain
  resources:
  - s3buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudf.cloudfdomain
  resources:
  - s3buckets/status
  verbs:
  - get
  - patch
  - update
