# permissions for end users to view s3buckets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: s3buckets-viewer-role
rules:
- apiGroups:
  - cloudf.cloudfdomain
  resources:
  - s3buckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudf.cloudfdomain
  resources:
  - s3buckets/status
  verbs:
  - get
